version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ltpmdb
      MYSQL_USER: bubu
      MYSQL_PASSWORD: bubu
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: adminer
    ports:
      - "8080:8080"

  apache:
    image: php:7.4-apache
    container_name: apache
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html/
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    entrypoint: >
      bash -c "a2enmod rewrite && docker-php-ext-install pdo pdo_mysql mysqli && apache2-foreground"

volumes:
  mysql_data: